version: '3.0'
services:
  backend:
    container_name: first.bar
    image: backend
    build: backend
    ports:
      - "8090:8090"

  backend2:
    container_name: secondary.bar
    image: backend
    build: backend
    ports:
      - "8091:8090"
  
  cypress:
    image: cypress/included:10.6.0
    entrypoint: ["/bin/sh", "-c"]
    environment:
     - "CYPRESS_baseUrl=${CYPRESS_baseUrl:-http://first.bar:8090/}"
     - "SECONDARY_URL=${SECONDARY_URL:-http://secondary.bar:8090/}"
    #  - "DEBUG=cypress:*"
    privileged: true
    volumes:
     - ./cypress/:/e2e/cypress/
     - ./cypress.config.js:/e2e/cypress.config.js:ro
     - ./package.json:/e2e/package.json:ro
     - ./yarn.lock:/e2e/yarn.lock:ro
     - node_modules:/e2e/node_modules
    working_dir: /e2e/
    command:
      - bash |
        yarn install &&
        npx wait-on -t 10000 $$CYPRESS_baseUrl &&
        npx cypress run --headless --env SECONDARY_URL="$$SECONDARY_URL" --browser chrome

volumes:
  node_modules:
